### ISSUE TITLE
Ajuda Error[1] = BattlePosition

### ISSUE THREAD

**Issue by kmex** [MuriloChianfa/TibiaAuto12#83]
fiz os procedimentos do OBS e na hora de configurar ele da erro de battleposition

start.py
Start in 1 Seconds...

Your Configure Stats: False
Coping Default Json

Health Location [X: 512 Y: 443]

Mana Location [X: 1055 Y: 306]

Battle Position Error

Status Bar Start [X: 1753, Y: 264]
Status Bar End [X: 1858, Y: 274]

Ring's Square Start [X: 1753, Y: 206]
Ring's Square End [X: 1784, Y: 237]

Amulet's Square Start [X: 1753, Y: 134]
Amulet's Square End [X: 1784, Y: 165]

MiniMap Start [X: 1753, Y: 5]
MiniMap End [X: 1858, Y: 113]

Size of MiniMap [X: 105, Y: 108]

Player Position [X: 872, Y: 405]

Game Window Start [X: 1, Y: 2]
Game Window End [X: 1744, Y: 809]

Size of Your SQM [Width: 116px, Height: 73px]

1° SQM Location [X: 756, Y: 478]
2° SQM Location [X: 872, Y: 478]
3° SQM Location [X: 988, Y: 478]
4° SQM Location [X: 756, Y: 405]
5° SQM Location [X: 872, Y: 405]
6° SQM Location [X: 988, Y: 405]
7° SQM Location [X: 756, Y: 332]
8° SQM Location [X: 872, Y: 332]
9° SQM Location [X: 988, Y: 332]

Some Errors Occurred... Opening The Manual Config.
Unfortunately, You Will Have To Manually Configure The Following Errors:

Error[1] = BattlePosition
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Calcifer\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\bot\Tibia\TibiaAuto12-master\modules\ChooseConfig.py", line 72, in bootstrap
    bootstrap()
  File "D:\bot\Tibia\TibiaAuto12-master\modules\ChooseConfig.py", line 421, in bootstrap
    ManualConfig(number_of_exceptions[i])
  File "D:\bot\Tibia\TibiaAuto12-master\modules\ChooseConfig.py", line 415, in ManualConfig
    ManualConfiguration.loop()
  File "D:\bot\Tibia\TibiaAuto12-master\core\GUI.py", line 75, in loop
    self.windowID.destroy()
  File "C:\Users\Calcifer\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2341, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Calcifer\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\bot\Tibia\TibiaAuto12-master\modules\__init__.py", line 76, in bootstrap
    ChooseConfig(selected_window.get())
  File "D:\bot\Tibia\TibiaAuto12-master\modules\ChooseConfig.py", line 513, in __init__
    self.window.loop()
  File "D:\bot\Tibia\TibiaAuto12-master\core\GUI.py", line 75, in loop
    self.windowID.destroy()
  File "C:\Users\Calcifer\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2341, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed

o meu arquivo NewConfig.json ficou assim:
{
  "Stats": false,
  "MouseOption": 0,
  "ItemsMode": "Frames",
  "Paths": {
    "MainPath": "images",
    "ItemsPath": "images/Items/Frames/",
    "ChestsPath": "images/Depot/Chests/",
    "ContainersNamePath": "images/Items/ContainersName/",
    "CavebotScriptsPath": "scripts/"
  },
  "Positions": {
    "LifePosition": [
      {
        "x": 512,
        "y": 443,
        "Stats": true
      }
    ],
    "ManaPosition": [
      {
        "x": 1055,
        "y": 306,
        "Stats": true
      }
    ],
    "BattlePosition": [
      {
        "x": 0,
        "y": 0,
        "Stats": false
      }
    ],
    "PlayerPosition": [
      {
        "x": 872,
        "y": 405,
        "Stats": true
      }
    ]
  },
  "Boxes": {
    "StatusBarBox": [
      {
        "x": 1753,
        "y": 264,
        "w": 1858,
        "h": 274,
        "Stats": true
      }
    ],
    "BattleBox": [
      {
        "x": 0,
        "y": 0,
        "w": 0,
        "h": 0,
        "Stats": false
      }
    ],
    "RingBox": [
      {
        "x": 1753,
        "y": 206,
        "w": 1784,
        "h": 237,
        "Stats": true
      }
    ],
    "AmuletBox": [
      {
        "x": 1753,
        "y": 134,
        "w": 1784,
        "h": 165,
        "Stats": true
      }
    ],
    "GameWindowBox": [
      {
        "x": 1,
        "y": 2,
        "w": 1744,
        "h": 809,
        "Stats": true
      }
    ],
    "MapBox": [
      {
        "x": 1753,
        "y": 5,
        "w": 1858,
        "h": 113,
        "Stats": true
      }
    ]
  },
  "SQM": {
    "SQM1": [
      {
        "x": 756,
        "y": 478,
        "Stats": true
      }
    ],
    "SQM2": [
      {
        "x": 872,
        "y": 478,
        "Stats": true
      }
    ],
    "SQM3": [
      {
        "x": 988,
        "y": 478,
        "Stats": true
      }
    ],
    "SQM4": [
      {
        "x": 756,
        "y": 405,
        "Stats": true
      }
    ],
    "SQM5": [
      {
        "x": 872,
        "y": 405,
        "Stats": true
      }
    ],
    "SQM6": [
      {
        "x": 988,
        "y": 405,
        "Stats": true
      }
    ],
    "SQM7": [
      {
        "x": 756,
        "y": 332,
        "Stats": true
      }
    ],
    "SQM8": [
      {
        "x": 872,
        "y": 332,
        "Stats": true
      }
    ],
    "SQM9": [
      {
        "x": 988,
        "y": 332,
        "Stats": true
      }
    ]
  }
}

**Comment by kmex** [comment]
desculpe criar um issue, eu não sabia que battle position era a janela dentro do game que tinha que estar aberta. vou testar o bot agora
